{%- import 'macros/copy-templates.yaml' as copy %}

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: master

  - name: template-repo-labels
    type: git
    check_every: 2m
    source:
      uri: https://github.com/qiime2/template-repo
      branch: master
      paths:
        - labels/*

  - name: template-repo-templates
    type: git
    check_every: 2m
    source:
      uri: https://github.com/qiime2/template-repo
      branch: master
      paths:
        - github_templates/*

  {%- for repo in repos %}
  - name: {{ repo }}-source
    type: git
    check_every: 24h
    source:
      uri: https://github.com/qiime2/{{ repo }}
      branch: master
  {%- endfor %}

jobs:
  - name: sync-labels
    public: true
    plan:
      - get: busywork
      - get: template-repo
        resource: template-repo-labels
        trigger: true
      - task: sync-labels
        file: busywork/extra/github/tasks/copy-labels.yaml
        params:
          GITHUB_USER: ((github_user))
          GITHUB_PASS: ((github_pass))
          REPOS: {{ ' '.join(repos) }}  # space is in $IFS for looping
  {%- for repo in repos %}
  - name: sync-{{ repo }}-templates
    public: true
    plan:
      - get: busywork
      - get: template-repo
        resource: template-repo-templates
        trigger: true
      - get: {{ repo }}-source
      - task: sync-templates
        config:
          {{- copy.make_linux_config(repo)|indent(10) }}
      - put: {{ repo }}-source
        params:
          repository: {{ repo }}-source-updated
          rebase: true
  {%- endfor %}
